# This triggers on all merged PRs into main

name: Main - Deploy

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    name: "[BUILD]"
    uses: faccomichele/utils-n-scripts/.github/workflows/lambda-build.yml@main
    with:
      working-directory: './lambda'
    secrets: inherit

  dev:
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    name: "[DEV]"
    uses: faccomichele/utils-n-scripts/.github/workflows/terraform-run.yml@main
    with:
      environment: 'dev'
      region: 'eu-central-1'
      working-directory: '.'
      action: 'apply'
      download-lambda-artifacts: true
      upload-output-artifact: true
    secrets: inherit

  dev-website:
    needs: dev
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    name: "[DEV-WEBSITE]"
    uses: faccomichele/utils-n-scripts/.github/workflows/deploy-website.yml@main
    with:
      environment: 'dev'
      region: 'eu-central-1'
      working-directory: './website'
    secrets: inherit

  stg-approval:
    needs: [dev-website]
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: "[STG-Approval]"
    runs-on: ${{ vars.RUNNERS || 'ubuntu-latest' }}
    environment: stg
    steps:
      - name: Awaiting approval for staging
        run: echo "Staging deployment awaiting environment approval"

  stg:
    needs: [build, dev, dev-website, stg-approval]
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    name: "[STG]"
    uses: faccomichele/utils-n-scripts/.github/workflows/terraform-run.yml@main
    with:
      environment: 'stg'
      region: 'eu-central-1'
      working-directory: '.'
      action: 'apply'
      download-lambda-artifacts: true
      upload-output-artifact: true
    secrets: inherit

  stg-website:
    needs: stg
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    name: "[STG-WEBSITE]"
    uses: faccomichele/utils-n-scripts/.github/workflows/deploy-website.yml@main
    with:
      environment: 'stg'
      region: 'eu-central-1'
      working-directory: './website'
    secrets: inherit

  prod-approval:
    needs: [stg-website]
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: "[PROD-Approval]"
    runs-on: ${{ vars.RUNNERS || 'ubuntu-latest' }}
    environment: prod
    steps:
      - name: Awaiting approval for production
        run: echo "Production deployment awaiting environment approval"

  prod:
    needs: [build, dev, dev-website, stg, stg-website, prod-approval]
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    name: "[PROD]"
    uses: faccomichele/utils-n-scripts/.github/workflows/terraform-run.yml@main
    with:
      environment: 'prod'
      region: 'eu-central-1'
      working-directory: '.'
      action: 'apply'
      download-lambda-artifacts: true
      upload-output-artifact: true
    secrets: inherit

  prod-website:
    needs: prod
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    name: "[PROD-WEBSITE]"
    uses: faccomichele/utils-n-scripts/.github/workflows/deploy-website.yml@main
    with:
      environment: 'prod'
      region: 'eu-central-1'
      working-directory: './website'
    secrets: inherit
