# This triggers on all PRs to validate the change using Terraform Plan

name: Pull Request - Validate

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:
    
concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  dev-build:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    name: "[DEV BUILD]"
    uses: faccomichele/gha-reusables/.github/workflows/lambda-build.yml@main
    with:
      environment: 'dev'
      region: 'us-east-1'
      working-directory: './lambdas'
      full-rebuild: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.full-rebuild == 'true' }}
    secrets: inherit

  dev:
    needs: dev-build
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    name: "[DEV]"
    uses: faccomichele/gha-reusables/.github/workflows/terraform-run.yml@main
    with:
      environment: 'dev'
      region: 'us-east-1'
      global: true
      working-directory: '.'
      lambda-working-directory: './lambdas'
      action: 'plan'
    secrets: inherit

  stg-build:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    name: "[STG BUILD]"
    needs: dev-build
    uses: faccomichele/gha-reusables/.github/workflows/lambda-build.yml@main
    with:
      environment: 'stg'
      region: 'us-east-1'
      working-directory: './lambdas'
      full-rebuild: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.full-rebuild == 'true' }}
    secrets: inherit

  stg:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    name: "[STG]"
    needs: stg-build
    uses: faccomichele/gha-reusables/.github/workflows/terraform-run.yml@main
    with:
      environment: 'stg'
      region: 'us-east-1'
      global: true
      working-directory: '.'
      action: 'plan'
    secrets: inherit

  prod-build:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    name: "[PROD BUILD]"
    needs: [dev-build, stg-build]
    uses: faccomichele/gha-reusables/.github/workflows/lambda-build.yml@main
    with:
      environment: 'prod'
      region: 'us-east-1'
      working-directory: './lambdas'
      full-rebuild: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.full-rebuild == 'true' }}
    secrets: inherit

  prod:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true) }}
    name: "[PROD]"
    needs: prod-build
    uses: faccomichele/gha-reusables/.github/workflows/terraform-run.yml@main
    with:
      environment: 'prod'
      region: 'us-east-1'
      global: true
      working-directory: '.'
      action: 'plan'
    secrets: inherit
