# This triggers on all PRs to validate the change using Terraform Plan

name: Pull Request - Validate

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  workflow_dispatch:
    inputs:
      full-rebuild:
        description: 'Perform a full rebuild (including Lambda packaging) instead of just applying the changes. Use this if you want to deploy changes to the Lambda code without making any changes to the Terraform configuration.'
        type: boolean
        default: false
            
concurrency:
  group: pr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  pull-requests: write
  contents: read

jobs:
  dev-build:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    name: "[DEV BUILD]"
    uses: faccomichele/gha-reusables/.github/workflows/lambda-build.yml@main
    with:
      environment: 'dev'
      region: 'us-east-1'
      working-directory: './lambdas'
      full-rebuild: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.full-rebuild == 'true' }}
    secrets: inherit

  dev:
    needs: dev-build
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    name: "[DEV]"
    uses: faccomichele/gha-reusables/.github/workflows/terraform-run.yml@main
    with:
      environment: 'dev'
      region: 'us-east-1'
      global: true
      working-directory: '.'
      lambda-working-directory: './lambdas'
      action: 'plan'
    secrets: inherit

  stg-wait-gate:
    needs: dev-build
    runs-on: ${{ vars.RUNNERS_AMD64 || 'ubuntu-latest' }}
    environment: stg-wait-gate
    steps:
      - name: Countdown to STG deployment
        run: echo "Waiting for STG deployment gate..."

  stg-build:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    name: "[STG BUILD]"
    needs: stg-wait-gate
    uses: faccomichele/gha-reusables/.github/workflows/lambda-build.yml@main
    with:
      environment: 'stg'
      region: 'us-east-1'
      working-directory: './lambdas'
      full-rebuild: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.full-rebuild == 'true' }}
    secrets: inherit

  stg:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    name: "[STG]"
    needs: stg-build
    uses: faccomichele/gha-reusables/.github/workflows/terraform-run.yml@main
    with:
      environment: 'stg'
      region: 'us-east-1'
      global: true
      working-directory: '.'
      action: 'plan'
    secrets: inherit

  prod-wait-gate:
    needs: [dev-build, stg-build]
    runs-on: ${{ vars.RUNNERS_AMD64 || 'ubuntu-latest' }}
    environment: prod-wait-gate
    steps:
      - name: Countdown to PROD deployment
        run: echo "Waiting for PROD deployment gate..."

  prod-build:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    name: "[PROD BUILD]"
    needs: prod-wait-gate
    uses: faccomichele/gha-reusables/.github/workflows/lambda-build.yml@main
    with:
      environment: 'prod'
      region: 'us-east-1'
      working-directory: './lambdas'
      full-rebuild: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.full-rebuild == 'true' }}
    secrets: inherit

  prod:
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    name: "[PROD]"
    needs: prod-build
    uses: faccomichele/gha-reusables/.github/workflows/terraform-run.yml@main
    with:
      environment: 'prod'
      region: 'us-east-1'
      global: true
      working-directory: '.'
      action: 'plan'
    secrets: inherit
